# Program to calculate Fibonnaci Series


### Programmer : Rafael Mata
### Date created: 02/14
### Date modified: 02/14

In [172]:
import time
import numpy as np

In [173]:
def fib(n):
     fib_series = [0, 1]
     for i in range(2, n):
          fib_series.append(fib_series[i-1] + fib_series[i-2])
     return fib_series

In [174]:
def fibonacci(n):
    # base case
    if n == 0:
        return 0
    elif n == 1:
        return 1
    # recursive case
    else:
        return fibonacci(n-1) + fibonacci(n-2)


In [175]:
def fibo(n):
    a = 0
    b = 1
    
    if n == 0:
        c = a
    elif n == 1:
        c = b
    else:
        c = b
    
    for i in range(2, n):
        c = a + b
        a = b
        b = c
        
    return c
        

In [176]:
# 
# Fast doubling Fibonacci algorithm (Python)
# by Project Nayuki, 2015. Public domain.
# https://www.nayuki.io/page/fast-fibonacci-algorithms
# 


# (Public) Returns F(n).
def fibona(n):
	if n < 0:
		raise ValueError("Negative arguments not implemented")
	return _fib(n)[0]


# (Private) Returns the tuple (F(n), F(n+1)).
def _fib(n):
	if n == 0:
		return (0, 1)
	else:
		a, b = _fib(n // 2)
		c = a * (b * 2 - a)
		d = a * a + b * b
		if n % 2 == 0:
			return (c, d)
		else:
			return (d, c + d)

In [224]:
i = 1
while i < 6:
  print(i)
  i += 1

1
2
3
4
5


In [248]:
n = 10000000

In [241]:
count = 0
while n > 0:
   
    n = n // 2
    count += 1
count

27

In [249]:
start_time = time.time()

r = fibona(n)

end_time = time.time()
elapsed_time = a = end_time - start_time

print("Elapsed time:", elapsed_time, "seconds")


Elapsed time: 3.329460859298706 seconds


In [245]:
import math
digits = int(math.log10(r))+1
digits

16719011

In [184]:
start_time = time.time()

fibo(n)

end_time = time.time()
elapsed_time = b = end_time - start_time

print("Elapsed time:", elapsed_time, "seconds")

Elapsed time: 52.66947388648987 seconds


In [35]:
start_time = time.time()

fib(n)

end_time = time.time()
elapsed_time = c = end_time - start_time

print("Elapsed time:", elapsed_time, "seconds")

Elapsed time: 0.00016307830810546875 seconds


In [36]:
v = np.arange(6)

In [50]:
fib(6)

[0, 1, 1, 2, 3, 5]

In [105]:
F = np.array([[1.0 ,1.0 ], [1.0 , 0.0]], dtype=np.longdouble)

In [106]:
F

array([[1., 1.],
       [1., 0.]], dtype=float128)

In [51]:
np.dot(F,F).dot(F)

array([[3, 2],
       [2, 1]])

In [152]:
R = np.linalg.matrix_power(F, 30000)

In [153]:
R

array([[inf, inf],
       [inf, inf]], dtype=float128)

In [154]:
r = fibo(15000000) 

KeyboardInterrupt: 

In [189]:
len(str(r))

4179753

In [190]:
r

KeyboardInterrupt: 

In [23]:
a / b

321923.68941979524

In [24]:
a/c

351298.4767225326

In [25]:
b/c

1.091247672253259